# application.yml
server:
  port: 8002

management:
  endpoints:
    web.exposure.include: '*'


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    locations: "classpath:migration"