version: '3.5'

networks:
  courses-network:

services:
  docker-product:
    image: docker.pkg.github.com/nestor-by/java-courses-2021/java:0.0.1
    ports:
      - '2888:8888'
    environment:
      ARTIFACT: "by.sp.cources:shop-order:0.0.1-ARTSYMENIA-SNAPSHOT"
      ARTIFACT_MAIN_CLASS: "by.part7.order.OrderApp"

      JAVA_OPTS: "-Dserver.port=8888 \
        -Dservice.customer=http://docker-customer:8888 \
        -Dservice.product=http://docker-product:8888 \
        -Dservice.product=http://docker-paymentInfo:8888"



  docker-paymentinfo:
    extends:
      file: docker-compose-base.yaml
      service: docker-java
    ports:
      - '2889:8888'
    environment:
      ARTIFACT: "by.sp.cources:shop-payment-info:0.0.1-ARTSYMENIA-SNAPSHOT"
      ARTIFACT_MAIN_CLASS: "by.part7.paymentInfo.PaymentInfoApp"

    networks:
      - courses-network