# application.yml
server:
  port: 8081

management:
  endpoints:
    web.exposure.include: '*'


spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    locations: "classpath:migration"